# Generated by Django 4.1.6 on 2023-08-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_district_is_active_division_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
